a = (input('Digite algo: '))
print('O tipo primitivo desse valor é ',type(a))
print('É uma alfabetico?', a.isalpha())
print('Esta em maiusculas? {}',a.isupper())
print('Esta em minusculas? {}',a.islower())
print('Esta capitalizada? {} ', a.istitle())
print('É um número {}', a.isnumeric())
print('Só tem espaços? {}', a.isspace())
print('É alfanumérico? {} ', a.isalnum())